package com.example.rucafeandriod;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Spinner;
import android.widget.Toast;

public class CoffeeActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener {
    String[] quantities = {"1", "2", "3", "4", "5"};
    private RadioGroup coffee_radio_group;
    private RadioButton short_btn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.coffee_select);

        // Set up radio group
        coffee_radio_group = (RadioGroup) findViewById(R.id.coffee_radio_group);
        coffee_radio_group.clearCheck();
        RadioButton defaultSize = (RadioButton) findViewById(R.id.short_btn);
        defaultSize.setChecked(true);


        // Set up spinner for quantities
        Spinner quantityList = (Spinner) findViewById(R.id.spinner2);
        quantityList.setOnItemSelectedListener(this);
        ArrayAdapter ad = new ArrayAdapter(this, android.R.layout.simple_spinner_item, quantities);
        ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        quantityList.setAdapter(ad);
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        // On selecting a spinner item
        String item = parent.getItemAtPosition(position).toString();

        // Showing selected spinner item
        Toast.makeText(parent.getContext(), "Selected: " + item, Toast.LENGTH_LONG).show();
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {
        // autogenerated, ignore for now
    }
}